name: Deploy the application to Google Cloud Run

on:
  push:
    branches:
      - 'master'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    env:
      appId: ${{ secrets.APPID }}
      baseUrl: ${{ secrets.BASEURL }}
      geoUsername: ${{ secrets.GEOUSERNAME }}
      geonamesApi: ${{ secrets.GEONAMESAPI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Build the Docker image
      - name: Docker Build and Test
        run: npm run docker:build
      # Tag the GCloud image
      - name: GCloud Tag
        run: npm run gcloud:tag
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: npm run gcloud:push

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: gcloud run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image gcr.io/local-weather-app-ce379/local-weather-app --platform managed --project local-weather-app-ce379 --region us-east1
